# Generated by Django 3.0.6 on 2020-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('Rap', 'Rap'), ('Pop', 'Pop'), ('Metal', 'Metal'), ('PostHardCore', 'PostHardCore'), ('Melodic Metalcore', 'Melodic Metalcore')], max_length=200)),
                ('logo', models.CharField(default='Band Logo place', max_length=1000)),
                ('description', models.CharField(default='Description here', max_length=1500)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
