# Generated by Django 3.0.6 on 2020-07-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fan',
        ),
    ]
