# Generated by Django 3.0.6 on 2020-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='email',
            field=models.EmailField(default='email here', max_length=100),
        ),
    ]
