# Generated by Django 3.0.6 on 2020-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200711_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='city',
            field=models.CharField(choices=[('Kiev', 'Kiev'), ('Lviv', 'Lviv'), ('Dnipro', 'Dnipro')], default='city', max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('Kiev', 'Kiev'), ('Lviv', 'Lviv'), ('Dnipro', 'Dnipro')], default='city', max_length=25),
        ),
    ]
