# Generated by Django 3.0.6 on 2020-07-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_event_fan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='fan',
        ),
        migrations.AddField(
            model_name='fan',
            name='event',
            field=models.ManyToManyField(blank=True, to='webapp.Event'),
        ),
    ]
