# Generated by Django 3.0.6 on 2020-07-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20200711_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='fan',
            name='description',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
